Repository AY2122S2-CS2113-T11-1/tp, pull requests merged in 2022-04, with the labels that each got.

#338 Fixes some PE-D bugs
  docs/UserGuide.md
  src/main/java/seedu/duke/command/eventcommands/AddEventCommand.java
  src/main/java/seedu/duke/command/eventcommands/DeleteEventCommand.java
  src/main/java/seedu/duke/eventlists/EventList.java
  src/main/java/seedu/duke/exceptions/EventDoesNotExist.java
  src/main/java/seedu/duke/exceptions/InvalidDeleteEventException.java
Labels: bug

#342 Fixes some PE-D bugs
  ListFolder/event_file.txt
  docs/UserGuide.md
  src/main/java/seedu/duke/command/eventcommands/AddEventCommand.java
  src/main/java/seedu/duke/eventlists/Event.java
  src/main/java/seedu/duke/eventlists/EventList.java
  src/main/java/seedu/duke/exceptions/EventExistsException.java
  src/main/java/seedu/duke/exceptions/InvalidDeleteEventException.java
  src/main/java/seedu/duke/exceptions/InvalidEventException.java
Labels: bug

#351 Aiman's PPP Draft added
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/aiman_assignment/profile-picture.jpg
  docs/team/aimanimtiaz.md
Labels: documentation

#363 Update code refactoring the parse method in the command parser class
  src/main/java/seedu/duke/CommandParser.java
Labels: type.Enhancement

#383 CommandParser for view commands separated
  src/main/java/seedu/duke/CommandParser.java
Labels: type.Task

#385 Help Command added to display everything
  src/main/java/seedu/duke/CommandParser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/eventcommands/ViewEventsCommand.java
Labels: type.Task

#393 Docs updated + Regex added
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/aiman-imtiaz.md
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/eventcommands/AddEventCommand.java
  src/main/java/seedu/duke/exceptions/InvalidAssignmentException.java
  src/main/java/seedu/duke/exceptions/InvalidDescriptionException.java
  src/main/java/seedu/duke/exceptions/InvalidEventException.java
  text-ui-test/EXPECTED.TXT
Labels: documentation, type.Enhancement

#420 Target audience section in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/aiman-imtiaz.md
Labels: documentation

#425 Commands added in manual testing
  ListFolder/assignment_list.txt
  ListFolder/housekeeper_file.txt
  docs/DeveloperGuide.md
Labels: documentation

#429 Constraint added on input string for help command
  ListFolder/event_file.txt
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/assigncommand/AssignHousekeeperCommand.java
  src/main/java/seedu/duke/command/eventcommands/ViewEventsCommand.java
  src/main/java/seedu/duke/exceptions/InvalidHelpException.java
  src/main/java/seedu/duke/exceptions/InvalidViewEventException.java
Labels: enhancement

#442 FAQ section removed from UG
  docs/UserGuide.md
  src/main/java/seedu/duke/exceptions/NameNotStringException.java
Labels: documentation

#444 Remove dups
  .gitignore
  src/main/java/seedu/duke/CommandParser.java
Labels: bug

#446 Running PR for adding and/or fixing docs before submission
  ListFolder/event_file.txt
  docs/UserGuide.md
Labels: documentation
